-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 14:14:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `default_schema` ;

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`party` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`party` (
  `PartyName` TEXT NOT NULL,
  `PartyTaxCode` TEXT NOT NULL,
  `PartyLogo` TEXT NOT NULL,
  `PLFirstName` TEXT NOT NULL,
  `PLLastName` TEXT NOT NULL,
  `PartyFoundingDate (dd-mm-yy)` TEXT NOT NULL,
  `PartyPolicy` TEXT NULL,
  PRIMARY KEY (`PartyName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`candidate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`candidate` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`candidate` (
  `NameTitle` TEXT NOT NULL,
  `CDFirstName` TEXT NOT NULL,
  `CDLastName` TEXT NOT NULL,
  `EduBackGround` TEXT NULL DEFAULT NULL,
  `Career` TEXT NOT NULL,
  `PartyName` TEXT NOT NULL,
  PRIMARY KEY (`CDFirstName`, `CDLastName`),
  CONSTRAINT `fk_candidate_party1`
    FOREIGN KEY (`PartyName`)
    REFERENCES `default_schema`.`party` (`PartyName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`district`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`district` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`district` (
  `DistrictName` TEXT NOT NULL,
  `DistrictOfficeName` TEXT NOT NULL,
  `DistrictOfficeAdd` TEXT NOT NULL,
  `ZipCode` INT(11) NOT NULL,
  PRIMARY KEY (`DistrictName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`districtofficetelephonenumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`districtofficetelephonenumber` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`districtofficetelephonenumber` (
  `DistrictOfficeTL` TEXT NOT NULL,
  `DistrictName` TEXT NOT NULL,
  PRIMARY KEY (`DistrictOfficeTL`),
  INDEX `fk_districtofficetelephonenumber_district1_idx` (`DistrictName` ASC) VISIBLE,
  CONSTRAINT `fk_districtofficetelephonenumber_district1`
    FOREIGN KEY (`DistrictName`)
    REFERENCES `default_schema`.`district` (`DistrictName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`elecplace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`elecplace` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`elecplace` (
  `SubDisName` TEXT NOT NULL,
  `ElecPlaceName` TEXT NOT NULL,
  PRIMARY KEY (`SubDisName`))
  INDEX `fk_ElecPlace_subdistrict1_idx` (`SubDisName` ASC) VISIBLE,
  CONSTRAINT `fk_ElecPlace_subdistrict1`
    FOREIGN KEY (`SubDisName`)
    REFERENCES `default_schema`.`subdistrict` (`SubDisName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`eleczone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`eleczone` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`eleczone` (
  `ElecNo` INT(11) NOT NULL,
  `Score` INT(11) NOT NULL,
  `PartyName` TEXT NOT NULL,
  PRIMARY KEY (`ElecNo`),
  INDEX `fk_eleczone_party1_idx` (`PartyName` ASC) VISIBLE,
  CONSTRAINT `fk_eleczone_party1`
    FOREIGN KEY (`PartyName`)
    REFERENCES `default_schema`.`party` (`PartyName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`list_of_prime_minister`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`list_of_prime_minister` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`list_of_prime_minister` (
  `PMNo` INT(11) NOT NULL,
  `NameTitle` TEXT NOT NULL,
  `PMFirstName` TEXT NOT NULL,
  `PMLastName` TEXT NOT NULL,
  `NoPeriod` INT(11) NOT NULL,
  PRIMARY KEY (`PMNo`),
  INDEX `fk_list_of_prime_minister_candidate1_idx` (`PMFirstName` ASC) VISIBLE,
  CONSTRAINT `fk_list_of_prime_minister_candidate1`
    FOREIGN KEY (`PMFirstName`)
    REFERENCES `default_schema`.`candidate` (`CDFirstName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`member_of_parliament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`member_of_parliament` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`member_of_parliament` (
  `eleczone_ElecNo` INT(11) NOT NULL,
  `MPNo` INT(11) NOT NULL,
  `PartyName` TEXT NOT NULL,
  `NameTitle` TEXT NOT NULL,
  `MPFirstName` TEXT NOT NULL,
  `MPLastName` TEXT NOT NULL,
  `PartyStatus` TEXT NOT NULL,
  PRIMARY KEY (`eleczone_ElecNo`, `MPNo`),
  INDEX `fk_member_of_parliament_eleczone1_idx` (`eleczone_ElecNo` ASC) VISIBLE,
  INDEX `fk_member_of_parliament_party1_idx` (`PartyName` ASC) VISIBLE,
  CONSTRAINT `fk_member_of_parliament_eleczone1`
    FOREIGN KEY (`eleczone_ElecNo`)
    REFERENCES `default_schema`.`eleczone` (`ElecNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_of_parliament_party1`
    FOREIGN KEY (`PartyName`)
    REFERENCES `default_schema`.`party` (`PartyName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`subdistrict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`subdistrict` ;

CREATE TABLE IF NOT EXISTS `default_schema`.`subdistrict` (
  `SubDisName` TEXT NOT NULL,
  `DistrictName` TEXT NOT NULL,
  `ElecNo` INT(11) NOT NULL,
  PRIMARY KEY (`SubDisName`,`DistrictName`, `ElecNo`),
  INDEX `fk_subdistrict_district1_idx` (`DistrictName` ASC) VISIBLE,
  INDEX `fk_subdistrict_eleczone1_idx` (`ElecNo` ASC) VISIBLE,
  CONSTRAINT `fk_subdistrict_district1`
    FOREIGN KEY (`DistrictName`)
    REFERENCES `default_schema`.`district` (`DistrictName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subdistrict_eleczone1`
    FOREIGN KEY (`ElecNo`)
    REFERENCES `default_schema`.`eleczone` (`ElecNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
